services:
  postgres:
    image: postgres:16-alpine
    container_name: devroast_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devroast
      POSTGRES_PASSWORD: devroast
      POSTGRES_DB: devroast
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
